In [4]:
%pip install seaborn

Collecting seabornNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (1.26.1)
Requirement already satisfied: pandas>=1.2 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.8.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.44.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\2004r\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

# Práctica 1 – Data Cleaning
## Dataset: Coffee Distribution Across 94 Countries

En esta práctica se realiza el proceso de limpieza y exploración inicial del dataset relacionado con la producción, consumo, importación y exportación de café en diferentes países.

El objetivo es analizar la calidad de los datos, detectar valores faltantes, duplicados y preparar el dataset para análisis posteriores.

## 1. Carga de librerías y dataset

En esta sección se importan las librerías necesarias para el análisis de datos y se carga el dataset utilizando Pandas.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
import pandas as pd

# cargar dataset
df = pd.read_csv("../dataset/psd_coffee.csv")

# mostrar primeras filas
df.head()

,Country,Year,Arabica Production,Bean Exports,Bean Imports,Beginning Stocks,Domestic Consumption,Ending Stocks,Exports,Imports,...,Production,Roast & Ground Exports,Roast & Ground Imports,Robusta Production,"Rst,Ground Dom. Consum",Soluble Dom. Cons.,Soluble Exports,Soluble Imports,Total Distribution,Total Supply
0,Albania,1960,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Albania,1961,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Albania,1962,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Albania,1963,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Albania,1964,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Ver cuántos datos tiene

In [7]:
df.shape

(6016, 21)

Ver nombres de las columnas

In [8]:
 df.columns

Index(['Country', 'Year', 'Arabica Production', 'Bean Exports', 'Bean Imports',
       'Beginning Stocks', 'Domestic Consumption', 'Ending Stocks', 'Exports',
       'Imports', 'Other Production', 'Production', 'Roast & Ground Exports',
       'Roast & Ground Imports', 'Robusta Production',
       'Rst,Ground Dom. Consum', 'Soluble Dom. Cons.', 'Soluble Exports',
       'Soluble Imports', 'Total Distribution', 'Total Supply'],
      dtype='object')

Ver información general del dataset

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6016 entries, 0 to 6015
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 6016 non-null   object
 1   Year                    6016 non-null   int64
 2   Arabica Production      6016 non-null   int64
 3   Bean Exports            6016 non-null   int64
 4   Bean Imports            6016 non-null   int64
 5   Beginning Stocks        6016 non-null   int64
 6   Domestic Consumption    6016 non-null   int64
 7   Ending Stocks           6016 non-null   int64
 8   Exports                 6016 non-null   int64
 9   Imports                 6016 non-null   int64
 10  Other Production        6016 non-null   int64
 11  Production              6016 non-null   int64
 12  Roast & Ground Exports  6016 non-null   int64
 13  Roast & Ground Imports  6016 non-null   int64
 14  Robusta Production      6016 non-null   int64
 15  Rst,Ground Dom. Consum  6016 non-null   int64
 16  Soluble Dom. Cons.      6016 non-null   int64
 17  Soluble Exports         6016 non-null   int64
 18  Soluble Imports         6016 non-null   int64
 19  Total Distribution      6016 non-null   int64
 20  Total Supply            6016 non-null   int64
dtypes: int64(20), object(1)
memory usage: 987.1+ KB

Ver estadísticas básicas

In [10]:
df.describe()

,Year,Arabica Production,Bean Exports,Bean Imports,Beginning Stocks,Domestic Consumption,Ending Stocks,Exports,Imports,Other Production,Production,Roast & Ground Exports,Roast & Ground Imports,Robusta Production,"Rst,Ground Dom. Consum",Soluble Dom. Cons.,Soluble Exports,Soluble Imports,Total Distribution,Total Supply
count,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.00000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000
mean,1991.500000,744.343251,814.576130,372.732547,457.242686,673.035239,449.392287,895.636968,430.320479,2.21127,1130.501164,13.163065,10.648105,383.946642,588.521443,84.513797,67.897773,46.054355,2018.064495,2018.064328
std,18.474489,3349.259676,2897.359439,3052.833589,3116.051164,3309.043485,3039.644305,3166.527239,3109.893157,20.44888,4433.006465,122.365592,61.176816,1929.120607,3136.536532,377.995317,347.229671,299.676010,7468.535501,7468.535544
min,1960.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1975.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1991.500000,0.000000,4.000000,0.000000,0.000000,14.000000,0.000000,9.000000,0.000000,0.00000,21.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.000000,0.000000,112.000000,112.000000
75%,2007.250000,200.000000,325.000000,0.000000,83.000000,227.000000,81.000000,439.000000,2.000000,0.00000,575.000000,0.000000,0.000000,27.000000,188.250000,1.000000,0.000000,0.000000,1105.250000,1105.250000
max,2023.000000,49700.000000,41689.000000,47000.000000,72461.000000,49070.000000,72461.000000,45675.000000,47000.000000,375.00000,69900.000000,2975.000000,1060.000000,30480.000000,47010.000000,6745.000000,4300.000000,6000.000000,97806.000000,97806.000000

## 3. Verificación de valores nulos

Se revisa si existen valores faltantes en el dataset para determinar si es necesario realizar algún proceso de imputación o eliminación de datos.

In [11]:
df.isnull().sum()

Country                   0
Year                      0
Arabica Production        0
Bean Exports              0
Bean Imports              0
Beginning Stocks          0
Domestic Consumption      0
Ending Stocks             0
Exports                   0
Imports                   0
Other Production          0
Production                0
Roast & Ground Exports    0
Roast & Ground Imports    0
Robusta Production        0
Rst,Ground Dom. Consum    0
Soluble Dom. Cons.        0
Soluble Exports           0
Soluble Imports           0
Total Distribution        0
Total Supply              0
dtype: int64

## 4. Verificación de registros duplicados

Se revisa si existen filas duplicadas que puedan afectar el análisis.

In [12]:
df.duplicated().sum()

0

Ver algunos países del dataset

In [13]:
df['Country'].unique()

array(['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Benin', 'Bolivia', 'Bosnia and Herzegovina',
       'Brazil', 'Burundi', 'Cameroon', 'Canada',
       'Central African Republic', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Ethiopia',
       'European Union', 'Gabon', 'Georgia', 'Ghana', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Honduras', 'India', 'Indonesia',
       'Iran', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Korea, South', 'Kosovo', 'Laos', 'Liberia', 'Madagascar',
       'Malawi', 'Malaysia', 'Mexico', 'Montenegro', 'Morocco',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Nigeria',
       'North Macedonia', 'Norway', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Russia', 'Rwanda',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore',
       'South Africa', 'Sri Lanka', 'Switzerland', 'Taiwan', 'Tanzania',
       'Thailand', 'Togo', 'Trinidad and Tobago', 'Turkey', 'Uganda',
       'Ukraine', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'Yemen', 'Yemen (Sanaa)', 'Zambia',
       'Zimbabwe'], dtype=object)

cuántos países distintos hay

In [14]:
df['Country'].nunique()

94

## 5. Limpieza de nombres de columnas

Los nombres de las columnas se estandarizan para facilitar el análisis posterior.  
Se convierten a minúsculas y se eliminan espacios y caracteres especiales.

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("&", "and")
df.columns = df.columns.str.replace(",", "")
df.columns = df.columns.str.replace(".", "")

df.columns

Index(['country', 'year', 'arabica_production', 'bean_exports', 'bean_imports',
       'beginning_stocks', 'domestic_consumption', 'ending_stocks', 'exports',
       'imports', 'other_production', 'production', 'roast_and_ground_exports',
       'roast_and_ground_imports', 'robusta_production',
       'rstground_dom_consum', 'soluble_dom_cons', 'soluble_exports',
       'soluble_imports', 'total_distribution', 'total_supply'],
      dtype='object')

In [16]:
df.head()

,country,year,arabica_production,bean_exports,bean_imports,beginning_stocks,domestic_consumption,ending_stocks,exports,imports,...,production,roast_and_ground_exports,roast_and_ground_imports,robusta_production,rstground_dom_consum,soluble_dom_cons,soluble_exports,soluble_imports,total_distribution,total_supply
0,Albania,1960,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Albania,1961,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Albania,1962,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Albania,1963,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Albania,1964,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 6. Guardado del dataset limpio

Finalmente, se guarda el dataset limpio para ser utilizado en las siguientes prácticas de análisis y modelado.

In [17]:
df.to_csv("../dataset/coffee_cleaned.csv", index=False)

Verificar valores extremos (outliers)

In [18]:
df.describe()

,year,arabica_production,bean_exports,bean_imports,beginning_stocks,domestic_consumption,ending_stocks,exports,imports,other_production,production,roast_and_ground_exports,roast_and_ground_imports,robusta_production,rstground_dom_consum,soluble_dom_cons,soluble_exports,soluble_imports,total_distribution,total_supply
count,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.00000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000,6016.000000
mean,1991.500000,744.343251,814.576130,372.732547,457.242686,673.035239,449.392287,895.636968,430.320479,2.21127,1130.501164,13.163065,10.648105,383.946642,588.521443,84.513797,67.897773,46.054355,2018.064495,2018.064328
std,18.474489,3349.259676,2897.359439,3052.833589,3116.051164,3309.043485,3039.644305,3166.527239,3109.893157,20.44888,4433.006465,122.365592,61.176816,1929.120607,3136.536532,377.995317,347.229671,299.676010,7468.535501,7468.535544
min,1960.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1975.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1991.500000,0.000000,4.000000,0.000000,0.000000,14.000000,0.000000,9.000000,0.000000,0.00000,21.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.000000,0.000000,112.000000,112.000000
75%,2007.250000,200.000000,325.000000,0.000000,83.000000,227.000000,81.000000,439.000000,2.000000,0.00000,575.000000,0.000000,0.000000,27.000000,188.250000,1.000000,0.000000,0.000000,1105.250000,1105.250000
max,2023.000000,49700.000000,41689.000000,47000.000000,72461.000000,49070.000000,72461.000000,45675.000000,47000.000000,375.00000,69900.000000,2975.000000,1060.000000,30480.000000,47010.000000,6745.000000,4300.000000,6000.000000,97806.000000,97806.000000

Guardar el dataset limpio

In [19]:
df.to_csv("../dataset/coffee_cleaned.csv", index=False)